language: bash

sudo: required

services:
  - docker

script:
  - docker build -t manuale .
  - docker run --rm manuale version
  - docker run --rm manuale -h
  - docker run --rm manuale true

after_script:
  - docker images

# vim:set et ts=2 sw=2:
